### ISSUE TITLE
Review Download Page

### ISSUE THREAD

**Issue by djoroya** [DeustoTech/dycon-platform#28]

**Comment by azaharmonge** [comment]
DyCon Toolbox is open source, compatible with MATLAB 9.3 (R2017b) or later, and is freely available on Github. 

### **Direct Download**

- Download DyCon Toolbox (.zip)

### **Download from MATLAB**

Alternatively you can start using DyCon Toolbox by simply pasting the code below to your MATLAB command window

unzip('https://github.com/DeustoTech/DyCon-Computational-Platform/archive/master.zip')
addpath(genpath(fullfile(cd,'DyCon-toolbox-master')))

### **Download from Github**

If you rather prefer to clone the repository directly from Github, you can do it by typing the following command at a terminal:

git clone https://github.com/DeustoTech/DyCon-Computational-Platform/archive/master.git

### **Give us your feedback**

Please if you find any bug or have questions, do not hesitate to contact us. You can give us your feedback through this email address (dycon-dev-group@deusto.es). 

### **Get started**

To get started we encourage you to visit First Steps where the basic features of DyCon Toolbox are explained. Then we suggest you to check any of our Tutorials.
