### ISSUE TITLE
Description of PDE and ODE Control. Examples main Page

### ISSUE THREAD

**Issue by djoroya** [DeustoTech/dycon-platform#29]
https://deustotech.github.io/dycon-platform-documentation/projects/03-examples

**Comment by azaharmonge** [comment]
Description of "Control of ODE"

%----------------------------------------TEX CODE -------------------------------------------------------
Given the ODE

\begin{align}
\left \{
\begin{array}{c}
x'(t) = f(t, x(t), u(t)), \  \  t \in [0,T], \\
x(0) = x_0,
\end{array}
\right. \nonumber
\end{align}
with $x(t)$ and $u(t)$ being the state and control variables respectively. The main goal is to find the control $u(t)$ that optimizes a certain functional $J(x(t),u(t))$. 

Summarizing, control of ODEs is crucial when the main interest is not to find the solution $x(t)$ of the ODE, but instead to optimize a certain quantity $J(x(t),u(t))$ with respect to the control variable $u(t)$ and subject to the ODE. 

%-------------------------------------------------------------------------------------------------------------

**Comment by azaharmonge** [comment]
Description of "Control of PDEs"

%------------------------------------------ TEX CODE -------------------------------------------------------
Control of PDEs can be approached by the DyCon Toolbox for all evolutionary PDEs that can be written in a semidiscrete form leading to the following finite dimensional system:

\begin{align}
\left \{
\begin{array}{c}
\frac{\partial x(t)}{\partial t} = L(t, x(t), u(t)), \  \  t \in [0,T], \\
x(0) = x_0,
\end{array}
\right. \nonumber
\end{align}
with $x(t)$ and $u(t)$ being the state and control variables respectively. The target is to find the control $u(t)$ that optimizes the functional $J(x(t),u(t))$ subject to the semidiscrete PDE.  
%----------------------------------------------------------------------------------------------------------------
